### ISSUE TITLE
Tried making a NHK Reader of my own

### ISSUE THREAD

**Issue by smachave** [halogenandtoast/nhk-reader-haskell#1]
Hello! I was inspired by this project and an android app that I use (Sync for NHK Easy News) and decided to create a web app. Here it is:

https://nhk.cryf.in/

I was in need of a reader which provided meanings of words on the same page that I could use from my PC. (You need to ~hover~ click on words to get their meanings).

**Comment by halogenandtoast** [comment]
Howdy, sorry I didn't see this earlier. That's pretty neat, what did you use for a source dictionary?

**Comment by halogenandtoast** [comment]
Howdy @tkshnwesper , sorry I didn't see this earlier. That's pretty neat, what did you use for a source dictionary?

**Comment by smachave** [comment]
I am using JMdict as the dictionary source. I wrote a small script to convert the XML format of JMdict into JSON:
https://github.com/tkshnwesper/JMdict-Parser
